name: crypto_app
description: "Crypto App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_riverpod: ^3.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  shared_preferences: ^2.4.12
  fl_chart: ^1.1.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  intl_utils: ^2.8.11

flutter:
  uses-material-design: true
  generate: true
