// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtGKa4aihw4eBOOqwNvcLHnBJqXROvMkw',
    appId: '1:1041216980445:web:e5c5c822e366c8ed93e234',
    messagingSenderId: '1041216980445',
    projectId: 'flutter-crypto-app-2941c',
    authDomain: 'flutter-crypto-app-2941c.firebaseapp.com',
    storageBucket: 'flutter-crypto-app-2941c.firebasestorage.app',
    measurementId: 'G-ZHPKT8Y214',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE6ZYLbLqWi8Y8lgelqXYU3WPjsqOt0Yo',
    appId: '1:1041216980445:android:fedca3ed781cc6ac93e234',
    messagingSenderId: '1041216980445',
    projectId: 'flutter-crypto-app-2941c',
    storageBucket: 'flutter-crypto-app-2941c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaddDgUhceGvXUkASSYkh8c4HyZoKoUMo',
    appId: '1:1041216980445:ios:38b09c6489d13b3e93e234',
    messagingSenderId: '1041216980445',
    projectId: 'flutter-crypto-app-2941c',
    storageBucket: 'flutter-crypto-app-2941c.firebasestorage.app',
    iosBundleId: 'com.gayuh.crypto.cryptoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaddDgUhceGvXUkASSYkh8c4HyZoKoUMo',
    appId: '1:1041216980445:ios:38b09c6489d13b3e93e234',
    messagingSenderId: '1041216980445',
    projectId: 'flutter-crypto-app-2941c',
    storageBucket: 'flutter-crypto-app-2941c.firebasestorage.app',
    iosBundleId: 'com.gayuh.crypto.cryptoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtGKa4aihw4eBOOqwNvcLHnBJqXROvMkw',
    appId: '1:1041216980445:web:d61609f98aa544ac93e234',
    messagingSenderId: '1041216980445',
    projectId: 'flutter-crypto-app-2941c',
    authDomain: 'flutter-crypto-app-2941c.firebaseapp.com',
    storageBucket: 'flutter-crypto-app-2941c.firebasestorage.app',
    measurementId: 'G-2ZDE6W775L',
  );
}
